# -*- coding: utf-8 -*-
"""latihan3_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c-LwyGHzE8Rrb8etSd-aCStouDQUpwNq
"""

def konversi(minggu=0):
    def hari(hari=0):
        def jam(jam=0):
            def menit(menit=0):
                total_menit = (minggu * 7 * 24 * 60) + (hari * 24 * 60) + (jam * 60) + menit
                return total_menit
            return menit
        return jam
    return hari

data = ["3 minggu 3 hari 7 jam 21 menit",
        "5 minggu 5 hari 8 jam 11 menit",
        "7 minggu 1 hari 5 jam 33 menit"]

def extract_integers(text):
    words = text.split()
    integers = list(filter(str.isdigit, words))
    return integers

filtered_data = [extract_integers(item) for item in data]

for item in filtered_data:
    minggu = int(item[0])
    hari = int(item[1])
    jam = int(item[2])
    menit = int(item[3])
    konvert = konversi(minggu)(hari)(jam)(menit)
    print(f"Data = {item}, hasil konversi = {konvert} menit")